'''版本号'''
__version__ = '1.0.0'
'''作者'''
__author__ = 'Zhenchao Jin'
'''标题'''
__title__ = 'sssegmentation'
'''描述'''
__description__ = 'sssegmentation is a general framework for our research on strongly supervised semantic segmentation'
'''链接'''
__url__ = 'https://github.com/SegmentationBLWX/sssegmentation'
'''邮件'''
__email__ = 'charlesblwx@gmail.com'
'''license'''
__license__ = 'MIT License'